### ISSUE TITLE
Question about the weight ratio of PatchNCE and SC 

### ISSUE THREAD

**Issue by jetitime** [cxa9264/CONFETII#1]
Hi @cxa9264 ,
  Sorry to distrub you. While reading the dacs.py file I found 'self.consistency_loss_weight = cfg.get('consistency_loss_weight', 5)', does this mean the loss in style transfer SC has a weight of 5? I would like to ask what is the weight of PatchNCE loss in style transfer? 
  Looking forward to your reply. Thank you very much!

**Comment by cxa9264** [comment]
Hello!

The *consistency_loss_weight=5* means the weight of the semantic consistency loss is $5$. The weights of other losses for GAN such as PatchNCE loss are still $1$ as defined in the config file.
