### ISSUE TITLE
Question about negative samples

### ISSUE THREAD

**Issue by jetitime** [cxa9264/CONFETII#2]
Dear @cxa9264 ,
    Sorry to bother you again. I found that the negative sample patches are randomly selected, which results in that some negative samples may not be content inconsistent with the anchor. For example, when the negative sample and the anchor are both road class, minimizing the contrast loss will increase the distance between the negative sample and the anchor, which is not conducive to generating high-quality images with consistent content. I want to know if there is a shortcoming in my understanding or if the article actually ignores the impact of such false negative samples. Looking forward to your reply. Thank you very much!

**Comment by cxa9264** [comment]
Hi,

Do you mean the contrastive loss in the style transfer model? The random selection comes from the CUT. It is true that the situation that you mention could happen, and there are several works after CUT that improve this process.

**Comment by jetitime** [comment]
Hi,
Thanks for your reply! Do you think the perceptual loss can mitigate the negative effects of randomly selecting negative samples in style transformation networks?

**Comment by cxa9264** [comment]
Hi,

It is possible. The perceptual loss introduces class information into the style transfer network training, which may help reducing the impact.
